name: Build
on:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout bookkeeping app
        uses: actions/checkout@v2
        with:
          path: 'app'

      - name: Checkout credentials repo
        uses: actions/checkout@v2
        with:
          repository: hemanta212/personal
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: "master"
          path: 'personal'

      - run: |
          git clone https://github.com/flutter/flutter.git
          cd flutter
      - run: echo ::add-path::`pwd`"/flutter/bin"

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - run: |
          cd app
          cp ../personal/credentials/inventory_flutter/google-services.json android/app/

          flutter pub get
          flutter build apk
          mkdir build/app/outputs/apk/app_release
          mv build/app/outputs/apk/release/*.apk build/app/outputs/apk/app_release/
          flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            app/build/app/outputs/apk/release/app-arm64-v8a-release.apk
            app/build/app/outputs/apk/release/app-armeabi-v7a-release.apk
            app/build/app/outputs/apk/release/app-x86_64-release.apk
            app/build/app/outputs/apk/app_release/app-release.apk
          body_path: app/CHANGELOG.txt
          tag_name: ${{ github.event.client_payload.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
